# Generated by Django 5.1.1 on 2024-09-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "song_id",
                    models.BigIntegerField(unique=True, verbose_name="곡일련번호"),
                ),
                ("rank", models.IntegerField(verbose_name="순위")),
                ("album_id", models.BigIntegerField(verbose_name="album_uid")),
                (
                    "album_name",
                    models.CharField(max_length=255, verbose_name="album_name"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="곡명")),
                ("artist_id", models.BigIntegerField(verbose_name="artist_uid")),
                (
                    "artist_name",
                    models.CharField(max_length=255, verbose_name="artist_name"),
                ),
                ("album_cover_url", models.URLField(verbose_name="커버이미지_주소")),
                ("lyrics", models.TextField(verbose_name="가사")),
                ("release_date", models.DateField(verbose_name="발매일")),
                ("likes", models.IntegerField(verbose_name="좋아요")),
                (
                    "genres",
                    models.ManyToManyField(
                        related_name="songs", to="melon.genre", verbose_name="장르"
                    ),
                ),
            ],
            options={
                "verbose_name": "노래",
                "verbose_name_plural": "노래들",
                "ordering": ["rank"],
            },
        ),
    ]
